import { Card } from "@/components/ui/card"
import Link from "next/link"
import { ArrowLeft } from "lucide-react"

export default function TermsPage() {
  return (
    <div className="flex flex-col">
      {/* Back Button */}
      <section className="py-8 px-4 sm:px-6 lg:px-8 border-b border-[var(--border-color)]">
        <div className="container mx-auto max-w-4xl">
          <Link
            href="/"
            className="inline-flex items-center text-[var(--silver)] hover:text-[var(--acid-lime)] transition-colors"
          >
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back to Home
          </Link>
        </div>
      </section>

      {/* Content */}
      <section className="py-20 px-4 sm:px-6 lg:px-8">
        <div className="container mx-auto max-w-4xl">
          <h1 className="text-5xl font-bold mb-4">Terms of Service</h1>
          <p className="text-[var(--silver)] mb-12">Last updated: November 11, 2025</p>

          <Card className="p-8 bg-[var(--slate)] border-[var(--border-color)]">
            <div className="prose prose-invert prose-lg max-w-none text-[var(--silver)] space-y-6">
              <p>
                Please read these Terms of Service ("Terms", "Terms of Service") carefully before using the <a href="https://detovalabs.xyz" className="text-[var(--acid-lime)] hover:underline">https://detovalabs.xyz</a> website (the "Service") operated by Detova Labs ("us", "we", or "our").
              </p>

              <h2 className="text-2xl font-bold text-[var(--off-white)] mt-8 mb-4">1. Agreement to Terms</h2>
              <p>
                By accessing or using the Service, you agree to be bound by these Terms. If you disagree with any part of the terms, then you may not access the Service.
              </p>

              <h2 className="text-2xl font-bold text-[var(--off-white)] mt-8 mb-4">2. AI-Powered Utilities</h2>
              <p>
                Our Service provides experimental AI-powered tools such as the "Pitch Polisher" and "Resume Heat Check" (the "AI Utilities"), which are powered by Google's Gemini API.
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li><strong>No Guarantees:</strong> These tools are for informational purposes only. The output is generated by an AI and is not guaranteed to be accurate, complete, or suitable for your specific needs.</li>
                <li><strong>No Professional Advice:</strong> The AI Utilities do not constitute professional, legal, financial, or career advice.</li>
                <li><strong>Your Responsibility:</strong> You are solely responsible for how you use the output from the AI Utilities.</li>
                <li><strong>Data Processing:</strong> When you use AI Utilities, your input is sent to the Gemini API for processing. We do not store your input data after processing is complete.</li>
              </ul>

              <h2 className="text-2xl font-bold text-[var(--off-white)] mt-8 mb-4">3. Internship Applications</h2>
              <p>
                When you submit an internship application through our Service:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>You confirm that all information provided is accurate and truthful.</li>
                <li>Submission of an application does not guarantee acceptance into the program.</li>
                <li>We reserve the right to accept or reject any application at our sole discretion.</li>
                <li>The internship program is subject to separate terms outlined in the Contributor Agreement.</li>
              </ul>

              <h2 className="text-2xl font-bold text-[var(--off-white)] mt-8 mb-4">4. User Content</h2>
              <p>
                When you submit content through our Service (applications, contact forms, newsletter sign-ups):
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>You retain all rights to your content.</li>
                <li>You grant us a license to use, store, and process your content to provide the Service.</li>
                <li>You are responsible for the content you submit.</li>
                <li>You must not submit content that is illegal, offensive, or infringes on others' rights.</li>
              </ul>

              <h2 className="text-2xl font-bold text-[var(--off-white)] mt-8 mb-4">5. Intellectual Property</h2>
              <p>
                The Service and its original content, features, and functionality are and will remain the exclusive property of Detova Labs. The Service is protected by copyright, trademark, and other laws of both the United States and foreign countries.
              </p>

              <h2 className="text-2xl font-bold text-[var(--off-white)] mt-8 mb-4">6. Third-Party Services</h2>
              <p>
                Our Service may contain links to third-party websites or services that are not owned or controlled by Detova Labs. We have no control over, and assume no responsibility for, the content, privacy policies, or practices of any third-party websites or services.
              </p>

              <h2 className="text-2xl font-bold text-[var(--off-white)] mt-8 mb-4">7. Disclaimer of Warranties</h2>
              <p>
                The Service is provided on an "AS IS" and "AS AVAILABLE" basis. Detova Labs makes no warranties, expressed or implied, regarding the Service, including but not limited to:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Accuracy, reliability, or availability of the Service</li>
                <li>Fitness for a particular purpose</li>
                <li>Non-infringement</li>
                <li>Uninterrupted or error-free operation</li>
              </ul>

              <h2 className="text-2xl font-bold text-[var(--off-white)] mt-8 mb-4">8. Limitation of Liability</h2>
              <p>
                In no event shall Detova Labs, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.
              </p>

              <h2 className="text-2xl font-bold text-[var(--off-white)] mt-8 mb-4">9. Termination</h2>
              <p>
                We may terminate or suspend your access to the Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.
              </p>

              <h2 className="text-2xl font-bold text-[var(--off-white)] mt-8 mb-4">10. Governing Law</h2>
              <p>
                These Terms shall be governed and construed in accordance with the laws of the United States, without regard to its conflict of law provisions.
              </p>

              <h2 className="text-2xl font-bold text-[var(--off-white)] mt-8 mb-4">11. Changes to Terms</h2>
              <p>
                We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material, we will try to provide at least 30 days' notice prior to any new terms taking effect.
              </p>

              <h2 className="text-2xl font-bold text-[var(--off-white)] mt-8 mb-4">12. Contact Us</h2>
              <p>
                If you have any questions about these Terms, please contact us:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>By email: <a href="mailto:hello@detovalabs.xyz" className="text-[var(--acid-lime)] hover:underline">hello@detovalabs.xyz</a></li>
                <li>By visiting this page on our website: <Link href="/contact" className="text-[var(--acid-lime)] hover:underline">/contact</Link></li>
              </ul>
            </div>
          </Card>
        </div>
      </section>
    </div>
  )
}